### ISSUE TITLE
Update to Unicode 10

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#519]

**Comment by KrasnayaPloshchad** [comment]
This would be helpful for Soyombo, Zanabazar and others.

**Comment by Kanjilearner817** [comment]
It appears that all of the new scripts of Unicode 10.0 except for Nǚshū ought to be routed through the USE.

**Comment by KrasnayaPloshchad** [comment]
UCDN is already updated to Unicode 10.0.

**Comment by behdad** [comment]
Fixed.  Will be in HarfBuzz 1.6.0.

**Comment by dscorbett** [comment]
This isn’t completely fixed, since commit 0faa16a did not update all of UCDN.

**Comment by behdad** [comment]
Should be good now.
